/*
 * This file was generated by @ffi-packager/ffi-packager v2.0.1.
 * https://github.com/node-ffi-packager
 *
 * Library: ogg
 * Conan.io recipe reference: ogg/1.3.4
 * Conan.io remote: conan-center
 * Conan.io package id: f2fe22dad08bad39aab2a38cb612e26da46e90c0
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function oggLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
